### PR TITLE
Unref msg data on a msgpack rpc response to prevent memleak

### PR DESCRIPTION
**Pull request by wmoors**
#19

### CODE REVIEW

**Comment by justinmk** [comment]
@wmoors in #19 it seems you have a repro case. How about adding a test? Then asan can catch it. 

cc @tarruda

**Comment by wmoors** [comment]
ping @tarruda , @justinmk 

I've added the specific test to leak_test.lua.

**Comment by justinmk** [comment]
Nice, thanks. @tarruda

**Comment by tarruda** [comment]
thanks @wmoors , sorry for the long delay

@justinmk I have published a new libmpack-lua release on luarocks, can you check if everything is working as expected? it has been a long time since I did this

**Comment by Bartel-C8** [comment]
Works here when installing on Ubuntu! (As apposed to version 1.0.8 which had missing sources, so 🥳 ). Thanks @tarruda !

**Pull request merged**
