### PR TITLE
Allow linking against system libmpack

### LINKED ISSUE #1: Allow linking against libmpack.so instead of including libmpack amalgamation
Building packages for distributions is difficult now that this has been split out of libmpack but requires libmpack's source to build.  At least for Debian, I was hoping I could just do the typical install [libmpack-dev]/[libmpack0] and then build libmpack-lua.

[libmpack-dev]: https://packages.debian.org/experimental/libmpack-dev
[libmpack0]: https://packages.debian.org/experimental/libmpack0

### PR DESCRIPTION
**Pull request by tarruda**
Also fix compilation with USE_SYSTEM_LUA=1 introduced by #4 

Close #1

### CODE REVIEW

**Comment by tarruda** [comment]
@jamessan can you test if this PR is enough to fix #1?

**Comment by jamessan** [comment]
I'll check it out tonight.

**Comment by chetgurevitch** [comment]
That works on arch linux. I've reworked the package for lua-mpack locally and wrote a new one for libmpack. I'll see about getting those changes into the official repos once this is merged. I also have some changes for the neovim package to bundle fewer dependencies and use ninja that I can try to get upstreamed while I'm at it.

**Comment by chetgurevitch** [comment]
Also sorry about the regression, was investigating some weird behavior that turned out to be an issue with arch's lua packaging. The fix just rolled out so behavior should be consistent with other distros now.

**Comment by jamessan** [comment]
Works great.  Thanks!

**Pull request merged**
