### PR TITLE
fix MacOS compilation

### PR DESCRIPTION
**Pull request by tarruda**
@Bartel-C8 can you confirm that this fixes the compilation issue?

### CODE REVIEW

**Comment by ismaell** [comment]
Maybe just define _XOPEN_SOURCE to 600 for everyone.

IMHO, it would be important to also document which APIs weren't exposed by setting it to 500. This might help to determine other issues with how the feature flags are implemented in Mac OS X.

**Comment by Bartel-C8** [comment]
Compilation works for me at least on Mac OS!

**Comment by akiletour** [comment]
Hello guys,

Do you have any news about this PR ?

Thanks :)

**Comment by hjdivad** [comment]
Fixed by #31

**Pull request closed without merging**
